<link href='https://fonts.googleapis.com/css?family=Exo:400,900' rel='stylesheet' type='text/css'>
<div class="wrapper">
  <div class="message">
    <h1>Keith A. Guernsey Portfolio</h1> 

    <div id= "projects">
    <a class= "btn btn-primary" id= "twitch" href='https://codepen.io/dudeguykid/full/OjZVGY/' target="_blank">Twitch API</a>
    <a class= "btn btn-primary" id= "weather" href='https://codepen.io/dudeguykid/full/prbjKB/' target="_blank">Local Weather</a>
    <a class= "btn btn-primary" id="pomodoro" href='https://codepen.io/dudeguykid/pen/prBKgm' target="_blank">Pomodoro Clock</a>
    <a class= "btn btn-primary" id= "jsCalc" href='https://codepen.io/dudeguykid/full/GvYMXN/' target="_blank">Javascript Calculator</a>
   <h2>about me</h2>
   <p1><img src="https://i.pinimg.com/originals/e9/80/67/e980677954d4b68b9a01bb962f674ab9.jpg" width="100" height="140">I am a proud husband and father of 1.5 kids. I live just west of Boston in a small adorable town called Grafton that I call the Stowe, VT of Mass. I am a product of small suburb of Boston, Arlington, where I lived in the very-much blue colar corner of the town and I am damn proud of that. 
  
I told myself after I finished my degree I would learn a new language so when it came time to choose that language by some devine intervention freeCodeCamp came into my life, and so began a multi-year passion project to learn all things JavaScript and Web Development.
    
I loved it, I loved everything about it and I just immersed myself in everything I could find about it, books, medium, twitter, podcasts, github, codepen, gitter, stackoverflow and it just wont stop and I still want more. 

My goal is to form a career around doing this. I know I'll have to start from the bottom but I need to start. I am surrounded by passionate people who love what they do and love coming to do it and I want very much to be one of those people! 
     </p1>
     </div>
  </div>
  <div id="footer">
<p2>Contact Info: </p2>
  <a class= "btn btn-primary" id= "twitter" href='https://www.twitter.com/dudeguykid/' target="_blank">Twitter</a>
  <a class= "btn btn-primary" id= "twitter" href='https://www.linkedin.com/in/keithaguernsey/' target="_blank">linkedIn</a>
    <a class= "btn btn-primary" id= "twitter" href='https://github.com/dudeguykid' target="_blank">GitHub</a>
  
  </div>
</div>
  
 
